LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := gralloc.mt6735m
LOCAL_SRC_FILES_64 := gralloc.mt6735m.so
LOCAL_SRC_FILES_32 := arm/gralloc.mt6735m.so
LOCAL_SHARED_LIBRARIES := libGLESv1_CM libgralloc_extra libhardware libion libion_mtk libstdc++
LOCAL_MULTILIB := both
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_PATH_32 := $($(TARGET_2ND_ARCH_VAR_PREFIX)TARGET_OUT_SHARED_LIBRARIES)/hw
LOCAL_MODULE_PATH_64 := $(TARGET_OUT_SHARED_LIBRARIES)/hw
include $(BUILD_PREBUILT)
