LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libh264enc_hw
LOCAL_SRC_FILES_64 := libh264enc_hw.a
LOCAL_SRC_FILES_32 := arm/libh264enc_hw.a
LOCAL_MULTILIB := both
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_SUFFIX := .a
include $(BUILD_PREBUILT)
